trigger:
- main

pool:
  vmImage: ubuntu-22.04

parameters:
 - name: BUNDLE_TARGET
   type: string
   default: dev
 - name: BUNDLE_ROOT
   type: string
   default: mlops_stacks/mlops_stacks


steps:
  - checkout: self

  - script: | 
      set -e
      curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
    displayName: Install databricks cli

  - script: |
      set -e
      databricks bundle validate -t ${{parameters.BUNDLE_TARGET}} --var="model_name=jh_test"
    displayName: Validate bundle
    workingDirectory: $(Agent.BuildDirectory)/s/${{parameters.BUNDLE_ROOT}}
    env:
      DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
      DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)

  - script: |
      set -e
      databricks bundle deploy -t ${{parameters.BUNDLE_TARGET}} --var="model_name=jh_test"
    displayName: Deploy bundle
    workingDirectory: $(Agent.BuildDirectory)/s/${{parameters.BUNDLE_ROOT}}
    env:
      DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
      DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)

  - script: |
      set -e
      databricks bundle run model_training_job --no-wait
      databricks bundle run batch_inference_job --no-wait
    displayName: Run bundle
    workingDirectory: $(Agent.BuildDirectory)/s/${{parameters.BUNDLE_ROOT}}
    env:
      DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
      DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
