parameters:
 - name: BUNDLE_TARGET
   type: string
 - name: BUNDLE_ROOT
   type: string
   default: bundle

jobs:
- job: Deploy_And_Run
  steps:
    - checkout: self

    - script: | 
        set -e
        make install-dependencies
      displayName: Install databricks cli
      workingDirectory: $(Agent.BuildDirectory)/s/${{parameters.BUNDLE_ROOT}}

    - script: |
        set -e
        make validate-bundle
      displayName: Validate bundle
      workingDirectory: $(Agent.BuildDirectory)/s/${{parameters.BUNDLE_ROOT}}
      env:
        DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
        DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
        BUNDLE_TARGET: ${{parameters.BUNDLE_TARGET}}

    - script: |
        set -e
        make deploy-bundle
      displayName: Deploy bundle
      workingDirectory: $(Agent.BuildDirectory)/s/${{parameters.BUNDLE_ROOT}}
      env:
        DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
        DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
        BUNDLE_TARGET: ${{parameters.BUNDLE_TARGET}}

    - script: |
        set -e
        make run-bundle-remote
      condition: eq('${{parameters.BUNDLE_TARGET}}', 'research')
      displayName: Run bundle
      workingDirectory: $(Agent.BuildDirectory)/s/${{parameters.BUNDLE_ROOT}}
      env:
        DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
        DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
        BUNDLE_TARGET: ${{parameters.BUNDLE_TARGET}}
